name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: '^0.5.0'
  firebase_analytics: '^6.0.0'
  firebase_auth: '^0.18.0+1'
  cloud_firestore: '^0.14.0+2'

  # google_sign_in:
  # apple_sign_in:
  get: ^3.4.1
  get_storage: ^1.2.1

  # flutter_platform_widgets:
  flutter_sheet_localization: ^1.0.0
  simple_gravatar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
